---
version: "3.9"
services:
  flexget:
    image: lscr.io/linuxserver/flexget:latest
    container_name: flexget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=EST
      - FG_LOG_LEVEL=info
      - FG_LOG_FILE=/config/flexget.log
      - FG_CONFIG_FILE=/config/.flexget/config.yml
      - FG_WEBUI_PASSWORD=somepasswordgoeshere #optional
    volumes:
      - ./config:/config
      - ./data:/data #optional
    ports:
      - 5050:5050
    restart: unless-stopped

