web_server:
  bind: 0.0.0.0
  port: 5050
  web_ui: yes

tasks:
  distrowatch-rss:
    rss:
      url: https://distrowatch.com/news/torrents.xml
      all_entries: no
    download: /data/distrowatch
    accept_all: yes

  linuxtracker-rss:
    rss:
      url: https://linuxtracker.org/rss_torrents.php?feed=dl&cat[]=563&pid=00000000000000000000000000000000
      all_entries: no
    download: /data/linuxtracker
    accept_all: yes

schedules:
  - tasks: [distrowatch-rss, linuxtracker-rss]
    interval:
      hours: 12
